name: Java CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile and Run
        run: |
          javac HelloDevOps.java
          java HelloDevOps


          - name: Build Docker Image
        run: docker build -t my-java-app:latest .
